### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Hasakev** [MattPChoy/MattPChoy#1]
<picture>
  <source
    srcset="https://github-readme-stats.vercel.app/api?username=mattpchoy&show_icons=true&theme=dracula"
    media="(prefers-color-scheme: dark)"
  />
  <source
    srcset="https://github-readme-stats.vercel.app/api?username=mattpchoy&show_icons=true&theme=transparent"
    media="(prefers-color-scheme: light), (prefers-color-scheme: no-preference)"
  />
  <img src="https://github-readme-stats.vercel.app/api?username=mattpchoy&show_icons=true" />
</picture>

**Comment by MattPChoy** [comment]
Hi Hasakev, 
Thanks for your valued contribution. I have now added this to my GitHub profile!
